### ISSUE TITLE
Remove this repo?

### ISSUE THREAD

**Issue by TimothyGu** [jstransformers/boilerplate#10]
Now that we have a Yeoman generator let's remove this.

**Comment by RobLoach** [comment]
Might be interesting to make [generator-jstransformer](http://github.com/jstransformers/generator-jstransformer) use this repository. Not sure how we'd go about that though.... I do find piping curl to gunzip sometimes faster than using `yo jstransformer`.

**Comment by RobLoach** [comment]
I find using Boilerplate makes it a lot easier to update repositories.

```
git clone git@github.com:jstransformers/jstransformer-stylus.git
cd jstransformer-stylus
git remote add boilerplate git@github.com:jstransformers/boilerplate.git
git fetch --all
git pull boilerplate master
```
