### ISSUE TITLE
Best Way To Update Transformers?

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/boilerplate#27]
RE: https://github.com/jstransformers/jstransformer-loader/issues/2

How do we update all the Transformers to the latest changes in Boilerplate in an easy fashion?

Some possible solutions:
- git: https://github.com/jstransformers/boilerplate/wiki#update
- @tunnckoCore suggested [khaos](https://www.npmjs.com/package/khaos), do you know if this supports updating packages?

**Comment by RobLoach** [comment]
Created a Khaos template for this at https://github.com/jstransformers/khaos-jstransformer ... It's still missing the ability to update JSTransformers from the latest in Boilerplate.

**Comment by RobLoach** [comment]
Found a better way to upgrade through git without the history....

```
git remote add boilerplate git@github.com:jstransformers/boilerplate.git
git pull boilerplate master
git add -A
git checkout -b boilerplate
// Fix conflicts
git add -A
git commit -m "Update Boilerplate"
git push origin boilerplate
```

**Comment by tunnckoCore** [comment]
Great, but their history is already messed :D 

Hm. What about some hooks?
Or @jdalton some thoughts? How you update all packages and repos of lodash, some automation?

**Comment by tunnckoCore** [comment]
@RobLoach https://github.com/rvagg/github-webhook-handler looks good.
Aaaand. hm... I think if we listen for `release` event it would be good, then we can gitclone repo, pull and and mark its release and even we can publish to npm, lol.

**Comment by tunnckoCore** [comment]
huh, it would work, i just cant realize which secret they want .. ;d

**Comment by RobLoach** [comment]
> @RobLoach https://github.com/rvagg/github-webhook-handler looks good.

This is if we have it automatically update for us through the GitHub webhook. We would need an external server for the webhook to hit. Not sure if this is something that we'd want to automate. As long as there's a documented workflow, then we'd be okay.

> we can use https://github.com/jonschlinkert/spawn-commands for multiple commands execution in the event listener, also https://github.com/tunnckoCore/gitclone for shorter git clone (damn when i'll get to that v2 release.. soo much months and todos lol)

Would be interesting to have a command in [Nuke](https://github.com/jstransformers/nuke) to update them all, but there are some conflicts you can run into when updating it. Manually has been easy, but not sure if it's something that could be automated.

I've updated [the Wiki with Update workflow](https://github.com/jstransformers/boilerplate/wiki#update) in place. It doesn't retain Boilerplate history.

**Comment by calebeby** [comment]
@RobLoach I am having trouble updating newly created transformers. (https://github.com/jstransformers/jstransformer-hjson) Because the wiki says to remove `.git` directory on initialization, git does not know how to merge them. I think it is best if we do keep the `.git` directory so that the histories stay related, and mergeable.

**Comment by RobLoach** [comment]
@calebeby You're right! Let's get rid of the `.git` removal step. Good catch.

**Comment by calebeby** [comment]
There are a few transformers that I made that I did this for. How do I reconnect their histories?

**Comment by RobLoach** [comment]
> There are a few transformers that I made that I did this for. How do I reconnect their histories?

No worries, they can take the same update approach. I just fixed the [Update notes](https://github.com/jstransformers/boilerplate/wiki#update) to reflect that. It's not a big change, just a bit more to fix then normal :wink:

**Comment by calebeby** [comment]
I figured out a way so that I don't have to do (as many) messy merges.

```
git checkout -b boilerplate
# associates history; doesn't actually merge anything
git pull https://github.com/jstransformers/boilerplate.git master --allow-unrelated-histories --strategy ours
git format-patch "c073b6d^..ee0729d" # do this in boilerplate repo to get new changes
git am -3 ../boilerplate/0001-Remove-Node.js-0.10-and-0.12-support.patch # apply changes
... repeat for other patch
```

**Comment by RobLoach** [comment]
Looks like you're applying patches? The git history is rather important here. Went through a round of updates, and added a script in Nuke:
https://github.com/jstransformers/nuke

Closing this for now, since it looks like everything is up to date.
