### ISSUE TITLE
Yeoman Generator

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/boilerplate#7]
@stoeffel was wondering about having a Yeoman Generator for this.

**Comment by stoeffel** [comment]
I will create a generator. If it's okay with you guys?

**Comment by TimothyGu** [comment]
SGTM

**Comment by ForbesLindesay** [comment]
More than ok :+1:

**Comment by stoeffel** [comment]
done https://github.com/jstransformers/generator-jstransformer

**Comment by RobLoach** [comment]
:+1:
